### ISSUE TITLE
Make pm.sample work with AR distribution

### ISSUE THREAD

**Issue by kori73** [pymc-devs/pymc4#298]
I am trying to build a simple AR(1) model as follows.

```
import pymc4 as pm
import numpy as np
np.random.seed(seed=42)

T = 100
y = np.zeros((T,))

for i in range(1,T):
    y[i] = 0.95 * y[i-1] + np.random.normal()

tau = 1.0
@pm.model
def model(y):
    beta = yield pm.Normal('beta', loc=0., scale=tau)
    likelihood = yield pm.AR('likelihood', num_timesteps=100, coefficients=[beta], level_scale=1.0, observed=y.reshape(-1, 1))
    #likelihood = yield pm.Normal('likelihood', loc=beta,scale=1.0, observed=y.reshape(-1, 1))
    return likelihood

trace = pm.sample(model(y), num_samples=10)
```
and getting the following error

```
2020-07-19 16:23:11.334593: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-07-19 16:23:11.356034: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x21b28077700 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-19 16:23:11.365104: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
C:\Users\koray.beyaz\Desktop\libs\pymc4\pymc4\pymc4\distributions\timeseries.py:59: UserWarning: At the moment, the Autoregressive distribution does not accept the initialization arguments: dtype, allow_nan_stats or validate_args. Any of those keyword arguments passed during initialization will be ignored.
  "At the moment, the Autoregressive distribution does not accept the initialization "
WARNING:tensorflow:From C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow_probability\python\sts\autoregressive.py:388: AffineScalar.__init__ (from tensorflow_probability.python.bijectors.affine_scalar) is deprecated and will be removed after 2020-01-01.
Instructions for updating:
`AffineScalar` bijector is deprecated; please use `tfb.Shift(loc)(tfb.Scale(...))` instead.
WARNING:tensorflow:From C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow_probability\python\distributions\linear_gaussian_ssm.py:467: LinearGaussianStateSpaceModel._initial_step_deprecated_behavior (from tensorflow_probability.python.distributions.linear_gaussian_ssm) is deprecated and will be removed after 2020-02-01.
Instructions for updating:
Previously, `initial_step` would return the value passed to the constructor, even if that value was not `Tensor`-like. This behavior is now deprecated. In the future, it will always return a `Tensor`-like object.
C:\Users\koray.beyaz\Desktop\libs\pymc4\pymc4\pymc4\distributions\timeseries.py:59: UserWarning: At the moment, the Autoregressive distribution does not accept the initialization arguments: dtype, allow_nan_stats or validate_args. Any of those keyword arguments passed during initialization will be ignored.
  "At the moment, the Autoregressive distribution does not accept the initialization "
WARNING:tensorflow:From C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\linalg\linear_operator_diag.py:166: calling LinearOperator.__init__ (from tensorflow.python.ops.linalg.linear_operator) with graph_parents is deprecated and will be removed in a future version.
Instructions for updating:
Do not pass `graph_parents`.  They will  no longer be used.
Traceback (most recent call last):
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 2494, in get_attr
    pywrap_tf_session.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'mcmc_sample_chain/dual_averaging_step_size_adaptation___init__/_bootstrap_results/NoUTurnSampler/.bootstrap_results/process_args/maybe_call_fn_and_grads/value_and_gradients/value_and_gradient/loop_body/PartitionedCall/pfor/PartitionedCall' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 331, in _MaybeCompile
    xla_compile = op.get_attr("_XlaCompile")
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 2498, in get_attr
    raise ValueError(str(e))
ValueError: Operation 'mcmc_sample_chain/dual_averaging_step_size_adaptation___init__/_bootstrap_results/NoUTurnSampler/.bootstrap_results/process_args/maybe_call_fn_and_grads/value_and_gradients/value_and_gradient/loop_body/PartitionedCall/pfor/PartitionedCall' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 2494, in get_attr
    pywrap_tf_session.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'Autoregressive_1/log_prob/scan/while/pfor/PartitionedCall' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 331, in _MaybeCompile
    xla_compile = op.get_attr("_XlaCompile")
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 2498, in get_attr
    raise ValueError(str(e))
ValueError: Operation 'Autoregressive_1/log_prob/scan/while/pfor/PartitionedCall' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 2494, in get_attr
    pywrap_tf_session.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'while' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 331, in _MaybeCompile
    xla_compile = op.get_attr("_XlaCompile")
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 2498, in get_attr
    raise ValueError(str(e))
ValueError: Operation 'while' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 2494, in get_attr
    pywrap_tf_session.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'while/while_body/cond' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 331, in _MaybeCompile
    xla_compile = op.get_attr("_XlaCompile")
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 2498, in get_attr
    raise ValueError(str(e))
ValueError: Operation 'while/while_body/cond' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 2494, in get_attr
    pywrap_tf_session.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'while/while_body/cond/PartitionedCall' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 331, in _MaybeCompile
    xla_compile = op.get_attr("_XlaCompile")
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 2498, in get_attr
    raise ValueError(str(e))
ValueError: Operation 'while/while_body/cond/PartitionedCall' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 2494, in get_attr
    pywrap_tf_session.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'Autoregressive_1/log_prob/scan/while/TensorArrayV2Write/TensorListSetItem/pfor/Tile' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 331, in _MaybeCompile
    xla_compile = op.get_attr("_XlaCompile")
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 2498, in get_attr
    raise ValueError(str(e))
ValueError: Operation 'Autoregressive_1/log_prob/scan/while/TensorArrayV2Write/TensorListSetItem/pfor/Tile' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ar1_test.py", line 19, in <module>
    trace = pm.sample(model(y), num_samples=10)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\pymc4\pymc4\inference\sampling.py", line 172, in sample
    results, sample_stats = run_chains(init_state, step_size)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 766, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 809, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 688, in _initialize
    *args, **kwds))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\function.py", line 2837, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\function.py", line 3194, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\function.py", line 3056, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 595, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\pymc4\pymc4\inference\sampling.py", line 162, in run_chains
    **(sample_chain_kwargs or dict()),
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow_probability\python\mcmc\sample.py", line 329, in sample_chain
    previous_kernel_results = kernel.bootstrap_results(current_state)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow_probability\python\mcmc\dual_averaging_step_size_adaptation.py", line 505, in bootstrap_results
    inner_results = self.inner_kernel.bootstrap_results(init_state)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow_probability\python\mcmc\nuts.py", line 500, in bootstrap_results
    init_state)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow_probability\python\mcmc\internal\leapfrog_integrator.py", line 368, in process_args
    target_fn, state_parts)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow_probability\python\mcmc\internal\util.py", line 293, in maybe_call_fn_and_grads
    result, grads = _value_and_gradients(fn, fn_arg_list, result, grads)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow_probability\python\mcmc\internal\util.py", line 278, in _value_and_gradients
    _, grads = tfp_math_value_and_gradients(fn, fn_arg_list)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow_probability\python\math\gradient.py", line 83, in value_and_gradient
    dydx = tf.gradients(ys=y, xs=xs, grad_ys=output_gradients)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 318, in gradients_v2
    unconnected_gradients)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 669, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 336, in _MaybeCompile
    return grad_fn()  # Exit early
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 669, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\function.py", line 711, in _rewrite_forward_and_call_backward
    forward_function, backwards_function = self.forward_backward(len(doutputs))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\function.py", line 620, in forward_backward
    forward, backward = self._construct_forward_backward(num_doutputs)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\function.py", line 668, in _construct_forward_backward
    func_graph=backwards_graph)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\function.py", line 658, in _backprop_function
    src_graph=self._func_graph)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 669, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 336, in _MaybeCompile
    return grad_fn()  # Exit early
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 669, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\function.py", line 711, in _rewrite_forward_and_call_backward
    forward_function, backwards_function = self.forward_backward(len(doutputs))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\function.py", line 620, in forward_backward
    forward, backward = self._construct_forward_backward(num_doutputs)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\function.py", line 668, in _construct_forward_backward
    func_graph=backwards_graph)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\function.py", line 658, in _backprop_function
    src_graph=self._func_graph)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 669, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 336, in _MaybeCompile
    return grad_fn()  # Exit early
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 669, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\while_v2.py", line 354, in _WhileGrad
    util.unique_grad_fn_name(body_graph.name), op, maximum_iterations)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\while_v2.py", line 626, in _create_grad_func
    body_graph_inputs, body_graph_outputs))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\while_v2.py", line 622, in <lambda>
    lambda *args: _grad_fn(ys, xs, args, body_graph),
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\while_v2.py", line 682, in _grad_fn
    unconnected_gradients="zero")
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 669, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 336, in _MaybeCompile
    return grad_fn()  # Exit early
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 669, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\cond_v2.py", line 120, in _IfGrad
    true_graph, grads, util.unique_grad_fn_name(true_graph.name))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\cond_v2.py", line 383, in _create_grad_func
    func_graph=_CondGradFuncGraph(name, func_graph))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\cond_v2.py", line 382, in <lambda>
    lambda: _grad_fn(func_graph, grads), [], {},
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\cond_v2.py", line 373, in _grad_fn
    src_graph=func_graph)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 669, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 336, in _MaybeCompile
    return grad_fn()  # Exit early
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 669, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\function.py", line 711, in _rewrite_forward_and_call_backward
    forward_function, backwards_function = self.forward_backward(len(doutputs))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\function.py", line 620, in forward_backward
    forward, backward = self._construct_forward_backward(num_doutputs)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\function.py", line 668, in _construct_forward_backward
    func_graph=backwards_graph)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\eager\function.py", line 658, in _backprop_function
    src_graph=self._func_graph)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 669, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 336, in _MaybeCompile
    return grad_fn()  # Exit early
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gradients_util.py", line 669, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\array_grad.py", line 828, in _TileGrad
    input_grad = math_ops.reduce_sum(array_ops.reshape(grad, split_shape), axes)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1907, in reduce_sum
    _ReductionDims(input_tensor, axis))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1918, in reduce_sum_with_dims
    gen_math_ops._sum(input_tensor, dims, keepdims, name=name))
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 10672, in _sum
    name=name)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 578, in _apply_op_helper
    param_name=input_name)
  File "C:\Users\koray.beyaz\Desktop\libs\pymc4\venv\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 61, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'input' has DataType variant not in list of allowed values: float32, float64, int32, uint8, int16, int8, complex64, int64, qint8, quint8, qint32, bfloat16, uint16, complex128, float16, uint32, uint64
```

Am I building the model incorrectly or the AR model is not working properly with pm.sample yet? If you think that this is a beginner-friendly issue, I would like to work on it.

**Comment by Sayam753** [comment]
Hi @kori73 
I tried fitting the model with ADVI. But ran into similar XLA issues. The traceback seems heavy to investigate. So, how about trying mcmc sampling with `xla=True`? 
Is this discourse [question](https://discourse.pymc.io/t/reproducing-pymc3-ar-1-tutorial-in-pymc4/5184) also related to this issue?

**Comment by kori73** [comment]
Hi @Sayam753, thanks a lot for the help. I am getting the same error with `xla=True` as well. And yes, the question is also related to this issue. I can delete the post or close the issue to avoid duplicated questions.

**Comment by Sayam753** [comment]
Thanks @kori73 for testing this out.
I suspect there's a bug in `AR` distribution. It would be great if you can help resolving this issue. This PR #220 is good to explore. Let's continue the discussion here and the discourse question can be updated after the issue is resolved.

**Comment by Sayam753** [comment]
Hi @kori73 
After discussing this issue with @ferrine , we figured out that using `tf.vectorized_map` while calculating log_prob results in all these errors. I have opened an issue [#1018](https://github.com/tensorflow/probability/issues/1018) on TFP side as well to gain insights. Let's wait for their response. Thanks.

**Comment by Sayam753** [comment]
Hi @kori73 
The issue on tensorflow side [#41789](https://github.com/tensorflow/tensorflow/issues/41789) is now resolved. Can you check if sampling works with latest tensorflow builds? Thanks

**Comment by kori73** [comment]
It is working now, thanks a lot @Sayam753.
